#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp "pod-babashka-etaoin" /tmp/release

VERSION=$(cat resources/POD_VERSION)

cd /tmp/release

## release binary as zip archive

zip "pod-babashka-etaoin-$VERSION-$BABASHKA_PLATFORM-amd64.zip" "pod-babashka-etaoin"

## cleanup

rm "pod-babashka-etaoin"
