#!/usr/bin/env bash

set -eo pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/gu" install native-image || true
export PATH=$GRAALVM_HOME/bin:$PATH

POD_NAME="pod-babashka-etaoin"
POD_REFLECTION_CONFIG="reflection.json"
POD_VERSION="$(cat resources/POD_VERSION)"

JAR="target/pod-babashka-etaoin-$POD_VERSION-standalone.jar"

echo "$POD_REFLECTION_CONFIG"

java -version
clojure -T:build uber

$GRAALVM_HOME/bin/native-image \
    -jar "$JAR" \
    -H:Name="$POD_NAME" \
    -H:+ReportExceptionStackTraces \
    -J-Dclojure.spec.skip-macros=true \
    -J-Dclojure.compiler.direct-linking=true \
    "-H:IncludeResources=POD_BABASHKA_SQL_VERSION" \
    -H:ReflectionConfigurationFiles="$POD_REFLECTION_CONFIG" \
    --initialize-at-build-time=.  \
    -H:Log=registerResource: \
    --verbose \
    --no-fallback \
    --no-server \
    --report-unsupported-elements-at-runtime \
    "-H:EnableURLProtocols=http,https" \
    "--enable-all-security-services" \
    "-J-Xmx4500m"
